### ISSUE TITLE
Does not properly kill the executable on rebuild in Windows

### ISSUE THREAD

**Issue by CameronAckermanSEL** [oxequa/realize#172]
On windows when realize detects that a file has been modified, it will correctly trigger a rebuild, but it is not guaranteed to kill the executable in such a way that releases socket bindings. This results in an error when the tool auto rebuilds:

![image](https://user-images.githubusercontent.com/14242948/38396996-0b3733cc-38f0-11e8-8ecd-a1c46fd81de3.png)

Is there a work around available for this?

**Comment by CameronAckermanSEL** [comment]
The configuration for my run command is nothing really special, it looks like

```
schema:
- name: ...
  path: .
  commands:
    build:
      status: true
      dir: cmd/exec
    run:
      status: true
      dir: cmd/exec
```
