### ISSUE TITLE
go clean not work

### ISSUE THREAD

**Issue by dfang** [oxequa/realize#175]
```
settings:
  legacy:
    force: true
    interval: 100ms
server:
  status: true
  open: true
  port: 5002
  host: localhost
schema:
- name: martini-example
  path: .
  commands:
    clean:
      status: true
    vet:
      status: true
    fmt:
      status: true
    test:
      status: true
    generate:
      status: true
    install:
      status: true
    build:
      status: true
    run:
      status: true
  watcher:
    paths:
    - /
    extensions:
    - go
    ignored_paths:
    - .git
    - .realize
    - vendor
    scripts:
      - type: before
        command: echo before global
        global: true
        output: true
      - type: before
        command: echo before change
        output: true
      - type: after
        command: echo after change
        output: true
      - type: after
        command: echo after global
        global: true
        output: true
```

server.go
```
package main

import (
	"github.com/go-martini/martini"
)

func main() {
	m := martini.Classic()
	m.Get("/", func() string {
		return "Hello world"
	})
	m.Run()
}
```

there is still an executable file in the project.

fmt also not work, is there something wrong with my config ?
