### ISSUE TITLE
Start long running process when realize starts

### ISSUE THREAD

**Issue by tonyalaribe** [oxequa/realize#182]
I have a usecase where i need to run some processes like Nats, and some other commands before realize starts. Is there any way to do this with realize? ie support for starting external commands

**Comment by Asoseil** [comment]
You can set a command under scripts
```
scripts:
      - type: before
        command: echo before global
        global: true
        output: true
```
