### ISSUE TITLE
main.go in subdirectory supported?

### ISSUE THREAD

**Issue by BastiPaeltz** [oxequa/realize#191]
Hey,

given the following directory structure:

```
.
├── server
│   ├── main.go
├── utils
│   └── utils.go
```

is it possible to build or run `server/main.go` but still be able to watch for changes in `server/` and `utils/`?

Thanks.

**Comment by mikegleasonjr** [comment]
Hi, I have my main in `cmd/api` and my config is this one:

```
settings:
schema:
- name: api
  path: cmd/api
  env:
    PORT: 3000
  commands:
    run:
      status: true
  watcher:
    extensions:
    - go
    paths:
    - ../..
    ignored_paths:
    - ../../vendor
```

**Comment by Asoseil** [comment]
yeah you can use ../ to watch a parent dir

**Comment by llonchj** [comment]
Using the following configuration gives me a ` exec: not started` error

```yaml
settings:
  legacy:
    force: false
    interval: 100s
server:
  status: false
  open: false
  port: 5001
  host: ""
schema:
- name: server
  path: server/cmd
  commands:
    run:
      status: true
  watcher:
    paths:
    - /
    - /../..
    extensions:
    - go
    ignored_paths:
    - .git
    - .realize
    - vendor
```
