### ISSUE TITLE
Realize with Delve

### ISSUE THREAD

**Issue by JorgeGarciaIrazabal** [oxequa/realize#196]
Is there a way to configure the `realize.yaml` to run with Delve debugger? (more info about the debugger [here](https://github.com/derekparker/delve) )

I tried this in the realize.yaml:

```
 commands:
    run:
      method: dlv debug -l=localhost:35173 --headless=true --api-version=2 --backend=default
      status: true
```

but it didn't work throwing this error:
`project not found`

**Comment by Nicolab** [comment]
Did you manage to work with Delve?

**Comment by JorgeGarciaIrazabal** [comment]
No, I had to create another server in a different Port  to be able to debug. But of course without the reload feature :(

**Comment by Nicolab** [comment]
Ok thanks for your reply.

_Realize_ doesn't works with Go 1.11 (go mod). Waiting to see if it evolves, I'll do with [modd](https://github.com/cortesi/modd) or [reflex](https://github.com/cespare/reflex).

**Comment by venkz** [comment]
> No, I had to create another server in a different Port to be able to debug. But of course without the reload feature :(

Hey can you help me understand what you meant by create another server? In realize.yml? Would be helpful if you can throw some light on this.

I am trying to do docker-compose up debug
and in the command section of this service, i have `"realize start -n='app-debug' "`

I get this error `project not found`

**Comment by mafuyuk** [comment]
Hey I was excited when I built a delve inside Dockerfile

Add
```
RUN go get -u github.com/go-delve/delve/cmd/dlv \
  && go build -o /go/bin/dlv github.com/go-delve/delve/cmd/dlv
```

.realize.yaml
```
schema:
- name: api
  path: .
  commands:
    install:
      status: true
      method: GO111MODULE=on GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -o api ./cmd/api
    run:	
      status: true
      method: /go/bin/dlv
  args:
    - exec
    - ./api
    - --headless=true
    - --listen=:2345
    - --api-version=2
```

Remember tosecurity_opt option in docker-compose.yml
```
security_opt:
      - seccomp:unconfined
```
