### ISSUE TITLE
Cannot do `--run` with go1.11 using go mod under windows.

### ISSUE THREAD

**Issue by DarthPestilane** [oxequa/realize#217]
------------ directory:
-- main.go
-- go.mod

main.go:

```go
package main

import "fmt"

func main() {
    fmt.Println("hello")
}
```

start realize:

```bash
realize start --run --nc
```

error shows:

```bash
[10:54:52][TEST] : Watching 1 file/s 0 folder/s
[10:54:52][TEST] : Install started
[10:54:52][TEST] : Install
 exec: not started
```

But when I remove go.mod, everything works fine.

**Comment by DarthPestilane** [comment]
realize version: 2.0.3

**Comment by chrisgoffinet** [comment]
Ok, glad I wasn't the only one experiencing this. I was going mad trying to figure out why this tool wouldnt work :)

**Comment by DarthPestilane** [comment]
And it's not only for windows, but mac also. Please fix this as soon as possible. Thanks!

**Comment by dlq84** [comment]
Same on Linux

**Comment by Nicolab** [comment]
Any news?

**Comment by mikegleasonjr** [comment]
If I recall correctly I was able to workaround by trying...

```
$ GO111MODULE=auto|off|on realize start ...
```

Can't remember which flag I set for `realize` to work..

**Comment by DarthPestilane** [comment]
I had to `go get -d github.com/oxequa/realize` and checkout to v2.0.2 then reinstalled manually. 
Finally, it works again.

But `realize --version` shows `Realize version 2.1`. Wired.

**Comment by llonchj** [comment]
related to #207

**Comment by Asoseil** [comment]
thanks for the support and for the reports, in the last months we had some company changes but in the first trimester 2019 we will release a new version

**Comment by zephinzer** [comment]
if anyone’s looking for a quick and dirty solution before this is resolved, i’ve put together some shell scripts into a makefile/docker image which you can find at https://github.com/zephinzer/golang-dev

**Comment by frederikhors** [comment]
@Asoseil everything ok? Is this project still alive?

**Comment by llonchj** [comment]
@frederikhors https://github.com/cortesi/modd

**Comment by evshiron** [comment]
I came up with this issue as well and worked out a solution. `realize` executes `go install` to rebuild your project into `$GOPATH/bin` first before actually running it. When you are using go modules, `go install` fails because there is no longer `$GOPATH`, thus "exec: not started".

As a workaround, you can modify your `.realize.yaml` like this:

```yaml
commands:
  install:
    status: true
    method: go build -o <path/to/built/binary>
  run:
    status: true
    method: <path/to/built/binary>
```

**Comment by unext-ray** [comment]
I happened to the same issue. Finally, I realized that the trash .go file was the troublemaker.
I used the feature of VSCode to generate history file to `.history` folder.
Inside `.history` folder there are a lot of `.go` files. After I added `.history` to ignore list `(.realize.yaml)`. Everything works well.
if someone also using the feature of VScode, you could have a try.
```
  watcher:
    extensions:
    - go
    paths:
    - /
    ignore:
      paths:
      - .git
      - .realize
      - vendor
      - .history
```

**Comment by xiangrui-zeng** [comment]
I happened to the same issue. Finally, I realized that the trash `.go` file was the troublemaker.
I used the feature of VSCode to generate history file to `.history` folder.
Inside `.history` folder there are a lot of .go files. After I added .history to ignore list `(.realize.yaml)`. Everything works well.
if someone also using the feature of VScode, you could have a try.
```
  watcher:
    extensions:
    - go
    paths:
    - /
    ignore:
      paths:
      - .git
      - .realize
      - vendor
      - .history
```
