### ISSUE TITLE
html changes not trigger rebuild

### ISSUE THREAD

**Issue by sikharis** [oxequa/realize#228]
Hi guys, I am using templating and html files in separate folder, changes in go extension are works, but not for html extensions.

Currently i am using windows and go version 1.11.
I am just curious, maybe my config are wrong.
hope you guys can help me, thanks.

```
settings:
  legacy:
    force: false
    interval: 0s
schema:
- name: netsecure
  path: .
  args:
  - "false"
  - --run
  - --no-config
  commands:
    install:
      status: true
	build:
      status: true
      dir: cmd
    run:
      status: true
      dir: cmd
  watcher:
    extensions:
    - go
	- html
    paths:
    - /
	- /html/layouts
	- /html/pages
    ignored_paths:
    - .git
    - .realize
    - vendor
```
