### ISSUE TITLE
install exec: not started

### ISSUE THREAD

**Issue by u007** [oxequa/realize#229]
ive a project based on go module, and on a new machine with latest realize, it somehow returns:

Watching 154 file/s 36 folder/s
[11:55:29][....] : Install started
[11:55:29][....] : Install 
 exec: not started

```
settings:
  files:
    outputs:
      status: false
      path: ""
      name: .r.outputs.log
    logs:
      status: false
      path: ""
      name: .r.logs.log
    errors:
      status: false
      path: ""
      name: .r.errors.log
  legacy:
    force: false
    interval: 0s
schema:
- name: mypro
  path: .
  commands:
    run:
      status: true
  args:
    - serve
  watcher:
    extensions:
    - go
    - graphql
    paths:
    - /
    ignore:
      paths:
      - .git
      - .realize
      - vendor
      - .idea
```

**Comment by frederikhors** [comment]
Same here. News?

**Comment by jhartman86** [comment]
Same thing as well. Downgrading to 2.0.1 works, but if you're using the latest release (eg. just doing `go get ...`), this error occurs.

**Comment by frederikhors** [comment]
@jhartman86 how to downgrade?

**Comment by jhartman86** [comment]
@frederikhors this is what worked for me (note, this is within Docker, using the `golang:1.11.3-alpine3.8` image):

```
#!/usr/bin/env bash

export GO111MODULE=off

cd ~/
go get github.com/oxequa/realize
cd /go/src/github.com/oxequa/realize && \
  git fetch && \
  git checkout v2.0.2 && \
  go get github.com/oxequa/realize

RV=$(realize --version)
echo "Realize installed @: $RV"

export GO111MODULE=on
```

Frankly, I've got no idea why checking out the tag and then running `go get ...` again works, but it does. YMMV

**Comment by yu19991013** [comment]
@frederikhors I've just solved this problem.
In your .realize.yaml, path is "."
As I wrote same setting, I got below error
```
exec: not started
```
So I changed path setting to below.
```
- name: mypro
  path: ./cmd/api/
```
Finally, realize could work without error.
I hope this comment helps your issue.

**Comment by annirudh** [comment]
If it helps, I'm on this commit:

```
commit bcf8507c0bd7d33f54a8223c9e8fa1fd3e4a4555 (HEAD -> master, origin/master, origin/HEAD)
Merge: c046dff 1a7c6b7
Author: Alessio Pracchia <asoseil@gmail.com>
Date:   Tue Sep 18 11:25:22 2018 +0200

    Merge pull request #212 from Quasilyte/quasilyte/sloppyLen

    realize: don't guard against negative length
```

**Comment by lehuuthoct** [comment]
I commented out watcher/path and it works fine.
![image](https://user-images.githubusercontent.com/9996518/63847138-80098980-c9d0-11e9-90b8-bb461d8e9f32.png)

**Comment by chjiyun** [comment]
didn't work for me , tired...
```
[13:26:05][GIN_APP] : Watching 5 file/s 1 folder/s
[13:26:05][GIN_APP] : Install started
[13:26:05][GIN_APP] : Install 
 exec: not started
```

**Comment by chjiyun** [comment]
@jhartman86   it works successfull, 666~

**Comment by fordguo** [comment]
the lasted version 2.0.3,have the same error.

**Comment by danielo515** [comment]
I am also having the same problem. I'm subscribing for a fix 😄

**Comment by benc-uk** [comment]
Same problem
Using it inside a container, get "exec: not started"

**Comment by patrickhener** [comment]
Same here, also subscribing for solution

**Comment by smithyj** [comment]
metoo
```
settings:
  legacy:
    force: false
    interval: 0s
schema:
- name: apiserver
  path: .
  commands:
    fmt:
      status: true
    run:
      status: true
      method: echo 1111
  watcher:
    extensions:
    - go
    paths:
    - /
    ignored_paths:
    - .git
    - .realize
    - vendor

```

**Comment by myhendry** [comment]
same issue for me. my .realize.yaml

```
settings:
  legacy:
    force: false
    interval: 0s
schema:
  - name: go-server
    path: .
    commands:
      run:
        status: true
    watcher:
      extensions:
        - go
      paths:
        - /
      ignored_paths:
        - .git
        - .realize
        - vendor
```

**Comment by jeffreylean** [comment]
adding go install work for me. 
`commands: 
    install:
        status: true
        method: go install
`

**Comment by jeffreylean** [comment]
Adding install under commands, works for me.
```
    commands:
      install:
        status: true
        method: go install
      run:
        status: true
```

**Comment by loloDawit** [comment]
Adding two things fixed this issue for me:
1. moving`main.go` to `cmd/server` dir 
2. adding the install command

```
schema:
- name: <your_project_name>
  path: ./cmd/server
  commands:
    install:
      status: true
      method: go install           
    run:    
      status: true
```
