### ISSUE TITLE
Question about setting up TDD with Docker.

### ISSUE THREAD

**Issue by HermannBjorgvin** [oxequa/realize#241]
I am trying to set up test driven development using realize to watch for file changes. I want to run tests after changes to the code. Specifically I am trying to set up a process like the Robert Martin three laws of TDD, write a failing test, pass the test, make a new requirement.

I am using a Docker development image in case it makes any difference. So far my `.realize.yaml` file looks like this:

```yaml
settings:
  legacy:
    force: true
    interval: 10ms
schema:
- name: /go/src/api
  path: /go/src/api
  commands:
    run:
      status: false
    test:
      status: true
      method: go test -v
  watcher:
    extensions:
    - go
    paths:
    - /
    ignored_paths:
    - .git
    - .realize
    - vendor
```

My docker-compose.yml file:

```yaml
version: '3.3'

services:
  api:
    command: realize start --test
    build: 
      context: ./api
      dockerfile: Dockerfile-dev
    ports:
      - 5000:3000
    volumes:
      - ./api:/go/src/api
```

I have tested `go test -v` and it runs my unit tests (currently just 1 test, very basic setup).

Does someone have an example they could share or point me in the right direction?
