### ISSUE TITLE
on window   can't work

### ISSUE THREAD

**Issue by RowgerGo** [oxequa/realize#245]
[ERROR] listen tcp :8083: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted

**Comment by RowgerGo** [comment]
```
settings:
  legacy:
    force: true
    interval: 0s
schema:
- name: autoBuild
  path: .
  commands: {}
  watcher:
    extensions:
    - go
    paths:
    - /
    ignored_paths:
    - .git
    - .realize
    - vendor
    scripts:
    - type: before
      command: taskkill /filestore-server [executable].exe /F
```

**Comment by Zioyi** [comment]
```yml
settings:
  legacy:
    force: true
    interval: 0s
schema:
- name: filestore-server
  path: .
  commands: {}
  watcher:
    extensions:
    - go
    paths:
    - /
    ignored_paths:
    - .git
    - .realize
    - vendor
    scripts:
    - type: before
      command: taskkill /IM filestore-server.exe /F
```
it work for me.
