### ISSUE TITLE
Ability to run a bash command on Reload

### ISSUE THREAD

**Issue by Mrcampbell** [oxequa/realize#250]
My project runs off a bash file, and so to run my app I run the command `./run -d` (`d` being a flag for "development").

Rather than running a `.go` file, this should be able to have a custom command at runtime.

**Comment by Mrcampbell** [comment]
I'm willing to work on this if there's nothing in the works!

**Comment by snassr** [comment]
For others looking here, you can already do that using the `scripts` key (It can be found in the readme config sample).
```
          scripts:
              - type: before
                command: echo hello before every reload
                output: true
```
The above runs the command on every reload. if you need it to run once, you can include global as follows:
```
          scripts:
              - type: before
                command: echo hello before any other command on startup only
                global: true
                output: true
``
