### ISSUE TITLE
Using realize with dockerised go+nginx app

### ISSUE THREAD

**Issue by BentCoder** [oxequa/realize#251]
Hi,

I am not sure if this is a realize issue or not but I would be much appreciated if someone could help.

I added realize to my go + nginx setup, but the requests breaks with `502` as shown below. Any idea what could be the solution to it?

```bash
Attaching to dev_hello_api_go_1, dev_hello_api_nginx_1

hello_api_go_1     | [12:13:47][APP] : Watching 2 file/s 9 folder/s

hello_api_nginx_1  | 2019/08/14 12:16:07 [error] 6#6: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: , request: "GET / HTTP/1.1", upstream: "http://172.18.0.8:8080/", host: "localhost:6000"
hello_api_nginx_1  | 172.18.0.1 - - [14/Aug/2019:12:16:07 +0000] "GET / HTTP/1.1" 502 157 "-" "PostmanRuntime/7.13.0" "-"
```

Thanks

---

```bash
.
├── .realize.yaml
├── cmd
│   └── server.go
├── docker
    └── dev
        ├── docker-compose.yaml
        ├── go
        │   └── Dockerfile
        └── nginx
            ├── Dockerfile
            └── app.conf

```
#### docker-compose.yaml
```yaml
version: "3.4"

services:

  hello_go:
    build:
      context: "../.."
      dockerfile: "docker/dev/go/Dockerfile"
    hostname: "hello-go"
    volumes:
      - "../..:/app"
    environment:
      PS1: "\\u@\\h:\\w\\$$ "

  hello_nginx:
    build:
      context: "../.."
      dockerfile: "docker/dev/nginx/Dockerfile"
    hostname: "hello-nginx"
    environment:
      PS1: "\\u@\\h:\\w\\$$ "
    ports:
      - "6000:80"
    depends_on:
      - "hello_go"
```

#### .realize.yaml
```yaml
settings:
  legacy:
    force: false
    interval: 0s
schema:
- name: app
  path: .
  commands: {}
  watcher:
    extensions:
    - go
    paths:
    - /
    ignore:
      paths:
      - .git
      - .realize
      - vendor

```
---

#### Dockerfile
```bash
FROM golang:1.12.7-alpine3.10

RUN apk update \
 && apk add --no-cache \
    git

WORKDIR /app

COPY . .

RUN go mod download \
 && go mod verify \
 && go build -o /server /app/cmd/server.go \
 && go get github.com/oxequa/realize

EXPOSE 8080

CMD ["realize", "start", "--path", "/server"]
```

#### server.go
```go
package main

import (
	"fmt"
	"log"
	"net/http"
)

func handler(w http.ResponseWriter, r *http.Request) {
	w.Write([]byte("Hello"))
}

func main() {
	http.HandleFunc("/", handler)
	fmt.Println("Server is running on port 8080 ...")
	log.Fatal(http.ListenAndServe(":8080", nil))
}
```
---
#### Dockerfile
```bash
FROM nginx:1.15.8-alpine

COPY docker/dev/nginx/app.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
```

#### app.conf
```bash
server {
    listen 80 default_server;

    location / {
        proxy_set_header X-Request-Id $request_id;
        proxy_set_header Host $host;

        proxy_pass http://hello_go:8080/;
    }
}
```
