### ISSUE TITLE
Panic in run phase

### ISSUE THREAD

**Issue by prats226** [oxequa/realize#260]
When I run realize from inside docker, there is no panic. Panics when running from outside. Same realize version in both environments.

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x10be1de]

goroutine 387 [running]:
os.(*Process).signal(0x0, 0x1654d80, 0x19a5830, 0x0, 0x0)
        /usr/local/go/src/os/exec_unix.go:56 +0x2e
os.(*Process).Signal(...)
        /usr/local/go/src/os/exec.go:131
github.com/oxequa/realize/realize.(*Project).run.func1(0xc0000c36a8)
        /Users/prats/workspace/src/github.com/oxequa/realize/realize/projects.go:581 +0x5d
github.com/oxequa/realize/realize.(*Project).run(0xc000128e00, 0xc000024e80, 0x13, 0xc000408d80, 0xc00019c000, 0x16504c0, 0xc00014e000)
        /Users/prats/workspace/src/github.com/oxequa/realize/realize/projects.go:646 +0xc5b
github.com/oxequa/realize/realize.(*Project).Reload.func3(0xc000128e00, 0xc000408d80, 0xc00019c000)
        /Users/prats/workspace/src/github.com/oxequa/realize/realize/projects.go:262 +0x147
created by github.com/oxequa/realize/realize.(*Project).Reload
        /Users/prats/workspace/src/github.com/oxequa/realize/realize/projects.go:260 +0x297
```

Realize version 2.0.3
go version go1.12.7 linux/amd64 (Inside docker)
go version go1.12.6 darwin/amd64 (outside)

yaml file:

```
settings:
  legacy:
    force: false
    interval: 0s
  schema:
  - name: test
    path: .
    commands:
      build:
        status: true
        method: go build -i -o test .
      run:
        status: true
        method: test
```
